[package]
name = "manga-alert"
version = "0.1.0"
authors = ["Matthew Dargan <matthewdargan57@gmail.com>"]
edition = "2021"
license = "BSD-3-Clause"

[dependencies]
chrono = "0.4.38"
reqwest = { default-features = false, features = ["blocking", "rustls-tls"], version = "0.12.4" }
scraper = "0.19.0"
